FooIbar/EhViewer

app/src/main/java/com/hippo/ehviewer/ui/scene/GalleryListScene.kt
=> Apply quick search in place if not in Popular

app/src/main/java/com/hippo/ehviewer/ui/scene/BaseScene.kt
=> Workaround for SideSheetDialog

app/src/main/java/com/hippo/ehviewer/ui/ConfigureActivity.kt, app/src/main/java/com/hippo/ehviewer/ui/legacy/SearchLayout.kt, app/src/main/java/com/hippo/ehviewer/ui/login/CookieSignInScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/login/SelectSiteScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/login/SignInScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/java/com/hippo/ehviewer/ui/scene/SearchBarScene.kt, app/src/main/java/com/hippo/ehviewer/ui/settings/AboutScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/settings/DownloadScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/settings/MyTagsScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/settings/UConfigScreen.kt, app/src/main/java/com/hippo/ehviewer/ui/webview/WebViewScreen.kt
=> Fix insets

app/src/main/java/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/java/com/hippo/ehviewer/ui/scene/GalleryListScene.kt
=> Scroll to top after refreshing

app/src/main/cpp/gifutils.c, app/src/main/java/com/hippo/ehviewer/EhApplication.kt, app/src/main/java/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/java/com/hippo/ehviewer/image/Image.kt, app/src/main/java/com/hippo/ehviewer/spider/SpiderDen.kt, gradle/libs.versions.toml
=> Do not modify the original file when rewriting GIF

.github/workflows/ci.yml, .github/workflows/releases.yml, app/build.gradle.kts, app/src/main/cpp/CMakeLists.txt, app/src/main/cpp/archive.c, app/src/main/cpp/gifutils.c, app/src/main/java/com/hippo/ehviewer/EhApplication.kt, app/src/main/java/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/java/com/hippo/ehviewer/image/Image.kt, app/src/main/java/com/hippo/ehviewer/jni/Archive.kt, app/src/main/java/com/hippo/ehviewer/jni/GifUtils.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/tachiyomi/data/release/GithubRelease.kt, app/src/main/java/tachiyomi/data/release/GithubWorkflow.kt
=> Use product flavors to provide marshmallow support

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Fix total pages not updating for new archives
Resolve #34
=> Skip `buildProvider` if the activity will restart

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryAdapter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryLoadStateAdapter.kt
=> Implement LoadStateAdapter for append/prepend load

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/res/values/styles.xml, gradle/libs.versions.toml
=> Implement splash screen

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/util/ExceptionUtils.kt
=> Fix large torrent list parsing

app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Use eh API as well if `forceEhThumb` is enabled

.github/workflows/ci.yml, .github/workflows/releases.yml, app/build.gradle.kts, build.gradle.kts, gradle.properties, gradle/libs.versions.toml, settings.gradle.kts
https://issuetracker.google.com/issues/307353433
=> Downgrade AGP to stable version but use newer lint

app/src/main/kotlin/com/hippo/ehviewer/ui/EhActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryCommentsScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt, app/src/main/kotlin/com/hippo/ehviewer/util/WindowInsetsUtil.kt, app/src/main/res/layout/scene_download.xml, app/src/main/res/layout/scene_favorites.xml, app/src/main/res/layout/scene_gallery_comments.xml, app/src/main/res/layout/scene_gallery_list.xml, app/src/main/res/layout/widget_content_layout.xml, app/src/main/res/values/dimens.xml, gradle/libs.versions.toml
=> Migrate from RikkaX Insets to Insetter

app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/SearchLayout.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/NormalSearch.kt
=> Set category chip min width and max items in each row

app/src/main/kotlin/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.kt
=> Fix unexpected touch scale behavior in PageViewer

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt
In a perfect world, material team should revise their spec and we don't need to do anything.
For now, we just choose to "violate" the spec.
=> Leave 56 dp minimum edge gap for navigation drawer

app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryPageApiParser.kt
=> Sync with upstream API changes

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/res/values/arrays.xml
=> Remember last viewed toplist

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt
=> Fix NPE caused by coroutine cancellation

app/src/main/kotlin/com/hippo/ehviewer/ui/GalleryInfoBottomSheet.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryCommentsScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/ClipboardUtil.kt
=> Fix crash when copying cookies

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt
=> Fix crash when navController is not initialized

app/src/main/res/values-v28/arrays.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Add missing color filter modes

app/src/main/kotlin/com/hippo/ehviewer/client/EhFilter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/DeferedComposable.kt
Resolve #125 
Resolve #126 
Resolve #132
=> Fix several issues in filter configuration screen

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt
This reverts commit b0896ea46582838d88a2f0b67ae0f3a3cc56c0ff.
Reason for revert: Regression
Resolve #103
=> Revert "Scroll to top after refreshing"

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt, app/src/main/kotlin/eu/kanade/tachiyomi/network/interceptor/UncaughtExceptionInterceptor.kt
=> Avoid uncaught exceptions crashing entire app

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryInfo.kt
=> Fix tag filters not working in thumbnail mode

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/HistoryScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/ProgressScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SceneCompose.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
=> fix fragment compose view memory leak

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/PreferenceWidgets.kt, app/src/main/kotlin/com/jamal/composeprefs3/ui/prefs/SliderPref.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Allow hiding comments below custom threshold

gradle/libs.versions.toml
=> Fix crash when deleting filters

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/HistoryScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/LocalTouchSlopProvider.kt
=> Reduce drawer and history item gesture sensitivity

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsScene.kt
=> Fix crash when clicking download notification

app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryHolder.kt, app/src/main/kotlin/com/hippo/ehviewer/util/FavouriteStatusRouter.kt
=> Fix incorrect favorite states in search results

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryPreviewFragment.kt
Honestly I don't think `parMap` is really needed since the server will just ban you if too aggressive.
=> Limit request concurrency

app/proguard-rules.pro
=> Fix crash caused by drawer state deserialization

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GallerySelectionTracker.kt
=> Fix crash when clicking retry button in favorites

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/GalleryDao.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt, app/src/main/kotlin/com/hippo/ehviewer/util/FavouriteStatusRouter.kt
=> Fix local favorites scroll state loss

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/GalleryDao.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/FastScroller.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt
What was the thought behind disabling placeholders at the beginning?
=> Fix local favorites list jumping

README.md, docs/README/zh-cn.md, docs/README/zh-tw.md
Did I miss anything to credit?
=> Update thanks and Traditional Chinese README

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt, app/src/main/kotlin/com/hippo/ehviewer/util/SDKUtils.kt
Tested with UP1A.231005.007, no bugs
=> Enable Predictive Back

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt
Source: https://github.com/ccloli/E-Hentai-Downloader/issues/256#issuecomment-1787322905
=> Append skip H@H key to original image url on retry

app/build.gradle.kts, app/proguard-rules.pro
=> Built-in proguard rules are obsolete, use our own

app/src/main/kotlin/com/hippo/ehviewer/ui/main/NormalSearch.kt
=> Reduce category min width for small screen devices

app/proguard-rules.pro
https://r8.googlesource.com/r8/+/04d49b152b624a437db46e17410bb1cb1e4dd809
=> Drop overloadaggressively

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt
=> Mitigate OOM for API < 26

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
=> Fix search bar text missing

app/src/main/kotlin/androidx/compose/material3/SearchBar2.kt
https://android-review.googlesource.com/c/platform/frameworks/support/+/2721593
=> Predictive Back for Compose SearchBar

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/BaseScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
=> Fix crash when initial composition hasn't been performed

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
Until we migrate GalleryListScene to compose
Resolve #242
=> Expose searchFieldState as workaround

app/src/main/kotlin/androidx/compose/material3/SearchBar2.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
=> Fix search bar width

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt
=> Fix favButton text not updating in gallery detail

app/src/main/kotlin/com/hippo/ehviewer/ui/tools/CircularLayout.kt
Idk why the author is wrong. Leave it alone.
=> Add rotate inertia for favSelectDialog

app/src/main/kotlin/com/hippo/ehviewer/ui/ConfigureActivity.kt
=> Tweak settings transition animations

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryCommentsFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/BBCodeTextToolbar.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/TextActionModeCallback.kt, app/src/main/res/menu/context_comment.xml
=> Restore common actions in comment field

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt
=> Fix crash when visiting newer version galleries

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
=> Fix advanced search not working

app/src/main/kotlin/androidx/compose/material3/NavigationDrawer2.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/PredictiveBack.kt
Following MDC NavigationDrawer design specs
=> Enhanced swipe-edge-oriented PredictiveBack

app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt
=> [Marshmallow] Fix OOM when decoding images

app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/FabLayout.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/FabLayout.kt
=> Fix invisible FAB being clickable

app/proguard-rules.pro, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt
=> Fix IME won't pop up after dismissing dialog

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListFragment.kt
Maybe we should use animation here?
=> Reset search bar offset on loading

app/src/main/kotlin/com/hippo/ehviewer/icons/big/Download.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsFragment.kt
=> Refine DownloadsScreen icons

app/src/main/kotlin/androidx/navigation/compose/NavHost.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/ConfigureActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/Theme.kt
=> Lowering default navAnim duration to 500ms

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/FavoritesFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListFragment.kt
=> Fix search bar scroll-away offset

app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/BaseScene.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/DownloadsFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryCommentsFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryDetailFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/SearchBarScene.kt, app/src/main/kotlin/com/hippo/ehviewer/util/ClipboardUtil.kt
`SnackbarDuration.Short` is already longer than `Snackbar.LENGTH_LONG`
=> Cleanup snackbar usage

app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListFragment.kt
=> Fix crash when TextField with focus is scaled to 0

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/ui/scene/GalleryListFragment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt, gradle/libs.versions.toml
Picker mode disabled due to crash.
https://issuetracker.google.com/issues/306193893
=> Compose DatePicker

app/src/main/AndroidManifest.xml, app/src/main/res/values-v26/bools.xml, app/src/main/res/values/bools.xml
=> Use large heap on API < 26

app/src/main/kotlin/com/hippo/ehviewer/client/EhUtils.kt
Memorized: 123594 nano
Unmemorized: 386927 nano
Debug mode
=> Reduce allocation for getCategoryColor

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
=> Refine DownloadsScreen

app/src/main/kotlin/com/hippo/ehviewer/ui/main/FabLayout.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
* Let Fablayout have consistent animation state, walk consistently
* Let Fablayout collapse when secondaryFab updated
* Move animation delay out of FabLayout, should not handle that within FabLayout
=> Refine Fablayout

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
=> Fix searchLayout close icon

app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/AdvanceTable.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/AdvancedSearch.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/ImageSearch.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/NormalSearch.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/LabeledCheckbox.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Make CheckBox/RadioButton text clickable and refine layout

app/build.gradle.kts, app/proguard-rules.pro, app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhRequestBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/ktbuilder/Okhttp.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, gradle/libs.versions.toml
This shouldn't be merged until 1.9.0 release
=> Move to Ktor, Part 1

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
=> Update history when viewing downloaded galleries

app/src/main/kotlin/com/hippo/ehviewer/updater/AppUpdater.kt, app/src/main/kotlin/tachiyomi/data/release/GithubCommit.kt
Fix parse error caused by invalid GitHub account
=> Use commit author name instead of login name

app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt
=> Don't scroll to top on refresh in local favorites

app/src/main/kotlin/androidx/compose/material3/NavigationDrawer2.kt
=> Make blur radius discrete to reduce overhead

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt
> Load limiting: 25 entries per request, 4-5 sequential requests usually okay before having to wait for ~5 seconds
https://ehwiki.org/wiki/API#Basics
=> Follow API rate limit to avoid IP ban

app/build.gradle.kts, app/proguard-rules.pro, app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/DiskCacheScoped.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/KtorHttpUriFetcher.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/MergeInterceptor.kt, app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt, app/src/main/kotlin/com/hippo/ehviewer/ktbuilder/Coil.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/CoilImageGetter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/DownloadCard.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/EhAsyncThumb.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/ImageSearch.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryPreviewScreen.kt, gradle/libs.versions.toml, settings.gradle.kts
https://github.com/coil-kt/coil/pull/1942
=> Move to Coil 3

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt
=> Fix unreleased lock

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
In case the gallery is taken down by DMCA.
Resolve #424
=> Update history regardless of availability

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
Resolve #513
This feels so hacky.
=> Workaround unable to exit search field on API < 28

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/com/hippo/ehviewer/util/Crash.kt
Idk if this works, like, if it's already OOM, will it have enough memory to perform a heap dump.
=> Dump heap on OOM

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
=> Fix crash when suggestions have the same keyword

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
=> Fix old download label not displayed when renaming

app/build.gradle.kts
As cookies are handled by ktor now
=> Strip okhttp's public suffix database

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt
`AlertDialog` does not support neutral button, so a checkbox is used instead.
=> Convert MainActivity dialogs to use DialogState

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/DownloadCard.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/DragHandle.kt
=> Refactor drag reordering

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt
=> Fix comments not showing after commenting

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt, app/src/main/kotlin/com/hippo/ehviewer/util/FDUtils.kt, app/src/main/kotlin/com/hippo/unifile/RawFile.kt, app/src/main/kotlin/com/hippo/unifile/UniFile.kt, app/src/main/kotlin/com/hippo/unifile/UniFileExtensions.kt
https://github.com/coil-kt/coil/issues/1970
=> Use ParcelFileDescriptor.open for RawFile, SAF sucks!

app/src/main/kotlin/androidx/compose/material3/Snackbar2.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt
=> Fix snackbar dismiss action color

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
=> Avoid detecting gallery URL copied from share menu

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
=> Fix crash in comment screen after leaving the app

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/dailycheck/DailyCheckWork.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt
=> Fix request news

README.md, app/build.gradle.kts, app/src/main/cpp/CMakeLists.txt, app/src/main/cpp/archive.c, app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/jni/Archive.kt, app/src/main/kotlin/com/hippo/ehviewer/jni/GifUtils.kt, app/src/main/kotlin/com/hippo/unifile/RawFile.kt, app/src/main/kotlin/com/hippo/unifile/UniFile.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, docs/README/zh-cn.md, docs/README/zh-tw.md
Not all archives are supported, but those from official sources (UTF-8 encoding zip) should be supported.
=> [Marshmallow] Archive support

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt
=> Fix download state not updating and crash

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/SettingsCollector.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt
Can't read the settings immediately as the edit is async.
Resolve #610
=> Fix delayed application of HTTP engine changes

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
=> Fix unable to move to first page on first attempt

app/src/main/kotlin/androidx/navigation/compose/NavHost.kt, app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
This reverts commit 0333a8c679256e36c74557a56349b3f539f03973.
Workaround for #578 #596
=> Revert "Always enable predictive nav"

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/FavoritesParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryListParser.kt, app/src/main/rust/src/parser/list.rs
=> Refine exception translation

app/src/main/kotlin/com/hippo/ehviewer/ui/main/SearchFilter.kt
Some devices will use secure keyboard for password input.
=> Don't use password type keyboard for number input

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
=> Fix uploader chip not clickable in thumbnail mode

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/ComicInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, gradle/libs.versions.toml
Fields may need to be discussed.
=> Generate ComicInfo.xml on download

app/src/main/kotlin/androidx/compose/material3/SearchBar2.kt
https://android-review.googlesource.com/c/platform/frameworks/support/+/2721593
=> Upstream SearchBar Predictive Back support

app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailUrlParser.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/ComicInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/DownloadScreen.kt
Maybe we merge SpiderInfo and ComicInfo and move startPage to db.
=> Restore download from ComicInfo.xml if available

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
`gid.cbz` is just a placeholder before the filename is decided.
=> Prepare to save downloaded gallery as cbz archive

gradle/libs.versions.toml
Reverts FooIbar/EhViewer#686
https://github.com/Calvin-LL/Reorderable/issues/8
=> Revert "Update dependency sh.calvin.reorderable:reorderable to v1.3.0"

app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt
Vising gallery page on e-hentai will show HV events as well.
=> Decouple hideHvEvents and requestNews settings

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
=> Initial support for third-party download manager

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/DownloadScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Generate ComicInfo.xml on archive download

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
=> Fix failed to generate ComicInfo.xml on API < 33

app/src/main/kotlin/com/hippo/ehviewer/ui/main/EhAsyncThumb.kt
ImageRequest is not Stable, each recompose will allocate an ImageRequest
=> Remember ImageRequest

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/com/hippo/ehviewer/SettingsCollector.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhTagDatabase.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/ArchiveParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryListUrlParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryNotAvailableParser.kt, app/src/main/kotlin/com/hippo/ehviewer/dailycheck/DailyCheckWork.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/login/PostLogin.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/DownloadScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/Crash.kt, app/src/main/kotlin/com/hippo/ehviewer/util/ExceptionUtils.kt, app/src/main/kotlin/com/hippo/ehviewer/util/OSUtils.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/kotlin/eu/kanade/tachiyomi/util/system/Logcat.kt, gradle/libs.versions.toml
https://github.com/FooIbar/EhViewer/issues/711#issuecomment-1937792720
=> Replace `printStackTrace` with proper priority log

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
It will only free about 1 MB memory
=> Don't trim gallery detail cache, Resolve #710

.github/workflows/ci.yml, .github/workflows/releases.yml
Not sure about gradle cache though.
=> Separate build tasks to accelerate CI

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/FabLayout.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/SnackBarPadding.kt
=> Refactor snackbarPadding

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt
=> Skip H@H on force retry

app/src/main/kotlin/com/hippo/ehviewer/client/EhTagDatabase.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/ListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/ImageSearch.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/unifile/UniFileExtensions.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
> 2024-02-11
> - The "similarity scan" function for file searches has been disabled since the algorithm used can no longer scale with the size of the database. We'll be looking into if this can be replaced with a better performing lookup.
=> Workaround for image search

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhRequestBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/util/KtorExtensions.kt, app/src/main/rust/src/lib.rs
=> Handle invalid UTF-8 characters in response body

app/src/main/cpp/natsort/strnatcmp.c
Filenames typically won't have decimals.
=> Ignore leading zeros when sorting archive entries

app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryPageParser.kt
=> Fix skip H@H key parsing

app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt
=> Fix forbidden filename characters in gallery title

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/HistoryDao.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/LocalFavoritesDao.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/HistoryScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
=> Implement title keyword search in history

app/schemas/com.hippo.ehviewer.dao.EhDatabase/21.json, app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/Database.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/GalleryFts.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/HistoryDao.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/LocalFavoritesDao.kt
BREAKING CHANGE: Upgrade database
Closes #806
=> Support FTS for history and local favorites search

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryApiParser.kt
Regression introduced in commit 4142f288
=> Fix simple language generation for ComicInfo

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
Before:
https://github.com/FooIbar/EhViewer/assets/118464521/587ecf74-a866-4c8e-9e33-d3907f421317
After:
https://github.com/FooIbar/EhViewer/assets/118464521/bd942d2a-177e-4b01-9387-b14903be568f
=> Workaround for prepending before the first item

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/setting/ReaderReadingModeSettings.kt
Another bug introduced in `DataStore` migration.
=> Fix general setting update on reading mode changes

app/schemas/com.hippo.ehviewer.dao.EhDatabase/22.json, app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhTagDatabase.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/BaseGalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryDetail.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/ListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryApiParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/Database.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/DatabaseMigrations.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/GalleryEntityFts.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/HistoryDao.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/LocalFavoritesDao.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/ComicInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsFilterState.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
BREAKING CHANGE: Upgrade database
Resolve #860 
Known limits:
- Tag namespaces are not supported
=> Initial support for local tag search

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/SliderPagerDoubleSync.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/VolumeKeysHandler.kt
TODO: Pan before move to the next page
=> Implement VolumeKeysHandler

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/SliderPagerDoubleSync.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/setting/ReadingModeType.kt
Fix this
https://github.com/FooIbar/EhViewer/assets/118464521/0fcc7df2-d948-4e56-9c81-bc5da22977fe
=> Make sure slider value has single source of truth

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
=> Workaround for crash on delete text button click

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
Should fix #883 in most cases.
=> Increase `bringCursorIntoView` workaround delay

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt
=> Fix concurrent modification

app/src/main/kotlin/com/hippo/ehviewer/download/SortMode.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
=> Implement group by download label

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt
=> Fix tag namespace for cloud favorites search

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ColorFilterSetting.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderGeneralSetting.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderModeSetting.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderPageSheet.kt
=> Make reader bottom sheet scrollable and fix insets

app/build.gradle.kts, app/src/main/kotlin/androidx/compose/material3/SearchBar2.kt
=> Pin compose foundation version to 1.7.0-alpha03

.github/workflows/ci.yml, .github/workflows/releases.yml, README.md, app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/updater/AppUpdater.kt, app/src/main/kotlin/com/hippo/ehviewer/util/AppConfig.kt, app/src/main/kotlin/tachiyomi/data/release/GithubRelease.kt, app/src/main/kotlin/tachiyomi/data/release/GithubWorkflow.kt, docs/README/zh-cn.md, docs/README/zh-tw.md
This reverts commit 5676de24da0cc8d77cdb98f0faf3bd9a810fb9d3.
Reason for revert: Desugaring causes regression on API 26+
Closes #905
=> Revert "Merge default and marshmallow flavors"

CHANGELOG.zh-CN.MD
=> Prepare changelog for 1.11.2

app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryInfo.kt
=> Fix generating simple language from title

app/build.gradle.kts
=> Fix false positive update notifications

app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt
=> Fix crash when reading galleries from gallery list

gradle/libs.versions.toml, settings.gradle.kts
=> Drop obsolete snapshot

gradle/libs.versions.toml, renovate.json
=> Downgrade to stable AGP

app/build.gradle.kts, app/src/main/kotlin/androidx/compose/material3/SearchBar2.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/SearchFilter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/HistoryScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/MainNav.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, gradle/libs.versions.toml, settings.gradle.kts
=> Update Compose to snapshot and remove workaround

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt
And optimize preloading strategy.
=> Fix `SpiderQueen` not respecting FIFO order

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
=> Fix download label not being draggable

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt
Fix fetch error being suppressed by decode job result.
=> Don't run decode job if fetch job failed

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt
=> Refactor database export

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadService.kt
=> Fix DownloadService stopped during `onFinish` call

app/src/main/kotlin/com/hippo/ehviewer/util/FDUtils.kt
=> Fallback to `transferTo` if `sendfile` failed

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt
=> Workaround for comment list lagging at the bottom

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/SearchFilter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/HistoryScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Modifier.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
It may crash on some devices.
Workaround for #996
=> Add option to disable list item animations

app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Prepare to migrate to https://github.com/adrielcafe/lyricist?
=> Rearrange code to move plurals resources together

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
=> Highlight selected item in select item dialog

app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
=> Fix titleless select item dialog top padding

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
=> Fixed crash on deleting a label after renaming it

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AboutScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, settings.gradle.kts
=> Update Compose snapshot

app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
| Before | After |
| --- | --- |
| ![1](https://github.com/FooIbar/EhViewer/assets/118464521/bace9415-398a-46c7-89e1-b9428132e158) | ![2](https://github.com/FooIbar/EhViewer/assets/118464521/e9b15708-bb1d-4382-8222-1c731e8fbfb1) |
=> Tweak select item dialog style

app/src/main/kotlin/com/hippo/ehviewer/ui/main/FabLayout.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/PredictiveBack.kt
https://android-review.googlesource.com/c/platform/frameworks/support/+/3040674
Btw what we can do for `NavHost` ?
=> Update predictive back animations to use interpolation curve of (0.1, 0.1, 0, 1)

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AboutScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Automatically backup data before updating

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/Widget.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ChapterNavigator.kt
=> Update to follow the latest material slider specs

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
=> Workaround for lazy layout lagging

app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
=> Avoid implement a `CancellableContinuation`

app/src/main/cpp/CMakeLists.txt
=> Switch back to GitHub xz repo

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/Context.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
https://github.com/Kotlin/KEEP/blob/context-parameters/proposals/context-parameters.md#standard-library-support
Conversions will land in following CL
=> Add fake `implicit` syntax for migration

.github/workflows/ci.yml, .github/workflows/releases.yml, app/build.gradle.kts, app/src/main/cpp/CMakeLists.txt, app/src/main/cpp/archive.c, gradle/libs.versions.toml
Cronet does not support it yet.
=> Update ndk and support 16 KB page sizes

app/src/main/kotlin/com/hippo/unifile/DocumentsContractApi21.kt, app/src/main/kotlin/com/hippo/unifile/MediaFile.kt, app/src/main/kotlin/com/hippo/unifile/RawFile.kt, app/src/main/kotlin/com/hippo/unifile/SingleDocumentFile.kt, app/src/main/kotlin/com/hippo/unifile/TreeDocumentFile.kt, app/src/main/kotlin/com/hippo/unifile/UniFile.kt
Also add comments on functions that rely on implementation details.
=> Refine UniFile and evict lookup cache on delete

app/build.gradle.kts
https://kotlinlang.org/docs/whatsnew-eap.html#generate-lambda-functions-using-invokedynamic
=> Drop `-Xlambdas=indy`

app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader2.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/ComicInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/FileUtils.kt, app/src/main/kotlin/com/hippo/unifile/RawFile.kt, app/src/main/kotlin/com/hippo/unifile/TreeDocumentFile.kt
https://android-review.googlesource.com/251120
=> `MimeTypeMap` is case-sensitive prior to Android O

app/build.gradle.kts
=> Revert "Drop `Xjvm-default=all`"

app/src/main/kotlin/com/hippo/ehviewer/util/LauncherUtils.kt
=> Don't fail silently if can't install update

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/UserConfigParser.kt, app/src/main/rust/src/parser/config.rs, app/src/main/rust/src/parser/mod.rs
=> Parse favorite categories from user config page

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
https://github.com/FooIbar/EhViewer/blob/78002dac3acf20ca3f73ead8f5799014e7c81a08/app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt#L314
What was this for?
=> Archive dialog overhaul

app/src/main/kotlin/com/hippo/ehviewer/ui/main/FundsItem.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Tweak image limits dialog

app/build.gradle.kts
Room generate kotlin by default now.
=> Drop obsolete flag

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/ArchiveParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/HomeParser.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/ArchiveList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/FundsItem.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/TorrentList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt
GalleryDetailScreen is too long
=> Move ArchiveList and TorrentList to separate files

.github/workflows/ci.yml, renovate.json
Address https://github.com/FooIbar/EhViewer/pull/1116#issuecomment-2092518517
=> Tweak CI & Renovate config

app/build.gradle.kts, app/src/main/kotlin/androidx/compose/material3/SideDrawer.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/SearchFilter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, gradle/libs.versions.toml, settings.gradle.kts
=> Update to snapshot Compose and remove workaround

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/BottomReaderBar.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderAppBars.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/BaseViewer.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
=> Correctly handle window insets in reader

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderGeneralSetting.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
This fixes https://github.com/FooIbar/EhViewer/pull/479#issuecomment-1847509388 as well.
=> Correctly handle display cutout

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/BottomReaderBar.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/setting/OrientationType.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/setting/PreferenceType.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/setting/ReadingModeType.kt
Avoid hard-coded width and offset.
=> Refactor bottom bar icon dropdown menus in reader

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
=> Fix tap control area shifting

app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader2.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PageActions.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
=> Fix crash when saving unloaded images

app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
=> Show gallery pages in thumbnail mode

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/HistoryScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/LocalTouchSlopProvider.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/SwipeToDismissBox2.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Reverts FooIbar/EhViewer#1152
Reason for revert: After some more testing I think sadly we still need it.
=> Revert "Drop experimental touch slop factor setting"

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt
=> Don't swallow exceptions when importing database

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt
=> Fix crash in favorites caused by duplicate items

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/SignInParser.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/login/SignInScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Autofill.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
CAPTCHA is no longer required.
=> Restore basic login and support autofill

app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryList.kt, settings.gradle.kts
https://issuetracker.google.com/340201510
=> Update Compose snapshot to fix item clipping

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AboutScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/AppConfig.kt, app/src/main/kotlin/com/hippo/ehviewer/util/Crash.kt
And use build time as initial update time.
=> Use CI update channel by default for snapshots

app/src/main/kotlin/com/hippo/ehviewer/client/parser/ParserUtils.kt, app/src/main/kotlin/com/hippo/ehviewer/util/ReadableTime.kt
We use thread-safe methods now.
=> Remove unnecessary synchronization

settings.gradle.kts
This reverts commit e6bdaf11728f17db7b961ad8da836e6302fe8116.
Reason for revert: https://issuetracker.google.com/341320533
=> Revert "Update Compose snapshot"

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/AppConfig.kt
=> Introduce `AppConfig.isSnapshot`

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
=> Replace invalid/consecutive whitespaces in query

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt
=> Fix navigation drawer overlapping side sheet

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
This is a regression introduced by 6277d7d.
Resolve #1267
=> Fix quick search and download label reordering

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/SDKUtils.kt
The mime type mapping for sqlite files was added in https://r.android.com/2988915.
=> Fix data export/import on Android V

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
https://github.com/FooIbar/EhViewer/pull/1288#discussion_r1638207311
=> Fix FAB recomposing on item selected

gradle/libs.versions.toml, settings.gradle.kts
=> Downgrade Compose to the last known good build

app/build.gradle.kts, app/src/main/kotlin/androidx/compose/foundation/gestures/AnchoredHorizontalDraggable.kt, app/src/main/kotlin/androidx/compose/material3/SideDrawer.kt, app/src/main/kotlin/androidx/compose/material3/fork/SwipeToDismissBox.fork.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/sh/calvin/reorderable/ReorderableLazyCollection.kt, app/src/main/kotlin/sh/calvin/reorderable/ReorderableLazyList.kt, app/src/main/kotlin/sh/calvin/reorderable/Scroller.kt, app/src/main/kotlin/sh/calvin/reorderable/draggable.kt, app/src/main/kotlin/sh/calvin/reorderable/util.kt, gradle/libs.versions.toml, settings.gradle.kts
As `animateItemPlacement` has been removed.
Apk size increased by ~3% due to https://r.android.com/3128916
Resolve #1284
=> Update Compose snapshot and vendor Reorderable

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/FileUtils.kt, app/src/main/kotlin/com/hippo/unifile/UniFileExtensions.kt
It will be replaced by three dots.
Resolve #1340
=> Don't use Unicode ellipsis character for filename

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
=> Limit search bar text to single line

app/src/main/kotlin/com/hippo/ehviewer/coil/DownloadThumbInterceptor.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader2.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PageActions.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/AppConfig.kt, app/src/main/kotlin/com/hippo/unifile/CachingFile.kt, app/src/main/kotlin/com/hippo/unifile/DocumentsContractApi21.kt, app/src/main/kotlin/com/hippo/unifile/MediaFile.kt, app/src/main/kotlin/com/hippo/unifile/RawFile.kt, app/src/main/kotlin/com/hippo/unifile/SingleDocumentFile.kt, app/src/main/kotlin/com/hippo/unifile/TreeDocumentFile.kt, app/src/main/kotlin/com/hippo/unifile/UniFile.kt, app/src/main/kotlin/com/hippo/unifile/UniFileExtensions.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Resolve #1356 
Is it worth it though?
=> Avoid relying on implementation details

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/DownloadScreen.kt
Tweak clean redundancy logic and add a confirm dialog.
Resolve #1369
=> Fix existing download dirname not being used

app/src/main/kotlin/com/hippo/ehviewer/client/data/ListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
This partially reverts commit 673c1837e9cc6371136d28f317a39554c6419860.
=> Implicitly add language filter tag

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadService.kt
I wonder if there are better ways
=> Fix download notification not showing

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PageActions.kt, app/src/main/kotlin/com/hippo/files/AndroidFileSystem.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
They are in seconds not milliseconds as per the documentation.
=> Fix MediaStore DATE_ADDED/DATE_MODIFIED

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/FavoritesParser.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
Resolve #1392 
Written in kotlin as the rust impl is ~2x slower (+0.3 ms), see https://github.com/FooIbar/EhViewer/actions/runs/9850661838.
Maybe we should reconsidering https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1139 for simple parsers that don't need jsoup.
=> Retrieve favorite notes when modifying favorites

app/src/main/kotlin/com/hippo/files/AndroidFileSystem.kt, app/src/main/kotlin/com/hippo/files/Paths.kt
This reverts commit ab2e4a8e2d01cfc66c655ce7559b80e561d35465.
=> Fix Path -> Uri conversion for paths contain '%'

gradle/libs.versions.toml
=> Revert "Update agp to v8.6.0-beta01"

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt
=> Fix comment screen refresh indicator padding

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/Utils.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Two things left: scale type in pager mode and navigation overlay
=> [New Reader] Misc improvements

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerItem.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/Utils.kt
We are close!
Don't know what's the point of landscape zoom when there's already smart fit.
Maybe we just remove it?
=> [New Reader] Implement custom image scale types

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt
The delay and animation are disrupting to me, thoughts?
=> [New Reader] Refine landscape zoom

app/src/main/kotlin/com/hippo/ehviewer/ui/main/SearchFilter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
> - Excessively narrow page range filters (min > 1000, max < 10, min/max > 0.5, min-max < 20) are no longer allowed.
https://forums.e-hentai.org/index.php?showtopic=261743
=> Update page range filter limit

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/DoubleTapZoom.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/NavigationOverlay.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerViewer.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/Utils.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/WebtoonViewer.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/viewer/ViewerNavigation.kt
So it won't take two actions to dismiss overlay & app bar.
=> Don't let navigation overlay consume click event

app/build.gradle.kts, app/src/main/kotlin/androidx/compose/material3/SearchBar.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/SearchFilter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
Also compile debug build with SDK 35 as sources for SDK 35 have been available.
Will reland the rest of #1474 after https://issuetracker.google.com/357042294 getting fixed.
=> Fix list item container color

app/src/main/kotlin/androidx/compose/foundation/scrollbar/ScrollbarAdapter.kt
=> Fix a division by zero error in ScrollbarAdapter

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
=> Fix read progress insert crash when exiting reader

app/src/main/kotlin/com/hippo/ehviewer/spider/ComicInfo.kt
=> Fix ComicInfo.xml for galleries with temp tags

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerItem.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt
=> Fix preload in reader

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerItem.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt
=> Refactor reader prefetch logic

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhCacheKeyFactory.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/MergeInterceptor.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Remove force e-hentai thumb option due to infeasible.
Resolve #1529 
CC @mirh for #77
=> Fix normal preview in exhentai

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/exception/NoHitsFoundException.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryList.kt, app/src/main/rust/src/parser/list.rs
=> Don't show load state indicator when no hits found

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt
=> Support scrolling with mouse wheel in reader

app/src/main/kotlin/com/google/accompanist/systemuicontroller/SystemUiController.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt
=> Adapt status bar content color for reader theme

app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt
This partially reverts commit 634269c6a492e3b02ce16847035d0f15628b8d9e.
Resolve #1561
=> Fix torrent count parsing

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/FilterScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/DropdownFilterChip.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/BottomReaderBar.kt, gradle/libs.versions.toml, settings.gradle.kts
This reverts commit c76440f167cc7a79476703a0647f33520a357b8d.
=> Switch to official Compose alpha BOM

app/src/main/kotlin/com/hippo/ehviewer/ui/Theme.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerViewer.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/WebtoonViewer.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/theme/Theme.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/WindowInsets.kt
=> Fix reader padding and progress indicator theme

gradle/libs.versions.toml
=> Revert "Update agp to v8.7.0-beta01"

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/files/AndroidFileSystem.kt, app/src/main/kotlin/com/hippo/files/Paths.kt
=> Fix unfinished files being considered downloaded

app/src/main/kotlin/com/hippo/ehviewer/ui/settings/EhScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/rust/src/parser/home.rs
=> Update description for IP-based image limit

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhRequestBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Replace custom user agent with desktop site option

app/src/main/rust/Cargo.lock, app/src/main/rust/Cargo.toml, app/src/main/rust/src/img/border.rs, app/src/main/rust/src/img/qr_code.rs, app/src/main/rust/src/lib.rs
Maybe we can remove the tag requirement since performance improves?
=> Switch to rxing for QR code detection

app/src/main/rust/src/img/qr_code.rs
=> Try to reduce false positives in ad detection

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt
=> Fix reader prefetch when scroll direction changes

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/DownloadArtistDao.kt
Legacy issue of E-Hentai's tag namespacing changes.
=> Fix galleries with both artist and cosplayer tags

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
=> Add scroll bar to quick search and download label

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt
=> Revert "Add scroll bar to quick search and download label"

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Use Downloads as start screen if device is offline

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/Dialog.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/LazyList.kt
This reverts commit a52ab28534c620d42a8e4c5196343a7b45c882a5.
Reland workaround for #1673 with fix
=> Reapply "Add scroll bar to quick search and download label"

CHANGELOG.zh-CN.MD, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
I'm planning to release 1.12.1, the fix for #1563 has been delayed for too long.
Anything to add?
=> Prepare changelog for 1.12.1

gradle/libs.versions.toml
=> Pin Compose Material3 version to 1.3

app/src/main/kotlin/com/hippo/ehviewer/client/EhCookieStore.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/HomeParser.kt, app/src/main/kotlin/com/hippo/ehviewer/icons/filled/Magnet.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Drop torrent download in favor of magnet links

app/src/main/kotlin/com/hippo/ehviewer/ui/main/RollingNumber.kt, app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/PageIndicatorText.kt
=> Introduce RollingNumberPlaceholder

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/ktor/OkhttpExtensions.kt, gradle/libs.versions.toml
=> Update OkHttp and configure async DNS

app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt
=> Fix preview parser

app/src/main/kotlin/com/hippo/ehviewer/ui/theme/Theme.kt
=> Fix crash on devices without WallpaperService

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/rust/src/lib.rs, app/src/main/rust/src/parser/fav.rs, app/src/main/rust/src/parser/list.rs
=> Show search warnings (if any) when no hits found

app/src/main/kotlin/com/hippo/ehviewer/client/data/BaseGalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/QrCodeInterceptor.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt, app/src/main/kotlin/com/hippo/ehviewer/ktbuilder/Coil.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerItem.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/GalleryAdsUtils.kt
This reverts commit https://github.com/FooIbar/EhViewer/commit/04ee1a6362e70370a1d286d177902b5693e0d3fb
Reason for revert: Obsoleted by the upcoming changes
=> Revert "Block AD in Large preview (#1694)"

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/ArchiveParser.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
Do not merge until the changes are deployed to e-hentai
=> Unify normal and small thumbnails parsing

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerItem.kt
=> Fix off-screen fetcher jobs blocking decode queue

app/src/main/kotlin/com/hippo/ehviewer/ktor/CronetEngine.kt
Some devices have corrupted Cronet
#1826
=> Disable Cronet on some incompatible devices

app/src/main/kotlin/com/hippo/files/AndroidFileSystem.kt
=> Fix false positive download failures on API 28

app/src/main/kotlin/com/hippo/ehviewer/ktor/CronetEngine.kt
It somehow got triggered on my device.
=> Log Cronet errors before restarting app

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/KeyEventHandler.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderGeneralSetting.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Support reverse physical key controls in reader

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader.kt
And increase PageLoader cache size on API 26+
=> Allow using RGB_565 on API < 26

app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/CoilImageGetter.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/LinkifyTextView.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryComment.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt
This reverts commit 62927cb6
Reason for revert: Bad performance
https://e-hentai.org/g/3145258/a192e3c0d1/#c6982074
=> Revert "Kill Legacy TextView (#1786)"

app/src/main/kotlin/com/hippo/ehviewer/ui/ComposeDefault.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/GalleryInfoBottomSheet.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/DeStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/EnStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/EsStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/FrStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/JaStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/KoStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/NbNoStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/Strings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/ThStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/TrStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/ZhCnStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/ZhHkStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/i18n/ZhTwStrings.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/ArchiveList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/AvatarIcon.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/TorrentList.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt
And add non-Compose accessor for Strings.
=> Match platform language resolution behavior

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderInfo.kt
=> Fix SpiderInfo serialization

app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt
=> Allow archives to have more pages than galleries

app/src/main/kotlin/com/hippo/ehviewer/client/EhTagDatabase.kt, app/src/main/res/values/arrays.xml
=> Refine tag database updating

app/src/main/kotlin/com/hippo/ehviewer/ui/main/DownloadCard.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/SharedElementTransition.kt
=> Disable shared element transition for DownloadCard

gradle/libs.versions.toml
=> Revert "Update aboutlibraries to v11.5.0"

app/src/main/kotlin/com/hippo/ehviewer/ui/login/WebViewSignInScreen.kt
Resolve #2132 
Why was `SideEffect` used in the first place?
=> Fix auto logout when logging in through WebView

gradle/libs.versions.toml
=> Revert "Update aboutlibraries to v11.6.0"

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
=> Fix lambdas in side sheet capturing outdated value

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DrawerContentStyle.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
=> Use different color for selected items

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/LicenseScreen.kt, gradle/libs.versions.toml, renovate.json
=> Update aboutlibraries to v12.0.0-b03

app/src/main/kotlin/com/hippo/ehviewer/client/EhUtils.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt
=> Show favorite status in grid view

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhCookieStore.kt, app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/exception/CloudflareBypassException.kt, app/src/main/kotlin/com/hippo/ehviewer/ktor/Common.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/login/PostLogin.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/login/WebViewSignInScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/util/WebViewExtensions.kt, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Use mobile UA for WebView to bypass Cloudflare

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/gallery/PageLoader.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerItem.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerViewer.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/Utils.kt
With the old strategy, prefetched images may be evicted from cache.
=> Use `LazyLayoutCacheWindow` API for prefetching

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
What about putting the add tag button in a floating toolbar?
=> Migrate to M3 Expressive medium flexible app bar

app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/MergeInterceptor.kt, app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/EhAsyncThumb.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryPreview.kt
- Fix potential memory cache miss
- Reduce `SizeResolver` allocations
- Make data source type more accurate
=> Image loading optimizations

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/client/data/BaseGalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/FavListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryComment.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryCommentList.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryDetail.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryTag.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryTagGroup.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/ListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/TagNamespace.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/HomeParser.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadService.kt, app/src/main/kotlin/com/hippo/ehviewer/shortcuts/ShortcutsActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/AdvanceTable.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsFilterState.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/State.kt, build.gradle.kts, gradle/libs.versions.toml
Also remove some unnecessary Parcelables.
Resolve #2347
=> Migrate from Parcelize to kotlinx.serialization

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/client/data/BaseGalleryInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/FavListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryComment.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryCommentList.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryDetail.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryTag.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryTagGroup.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/ListUrlBuilder.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/TagNamespace.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/HomeParser.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadService.kt, app/src/main/kotlin/com/hippo/ehviewer/shortcuts/ShortcutsActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/CommonOperations.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/AdvanceTable.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsFilterState.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryCommentsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/tools/State.kt, build.gradle.kts, gradle/libs.versions.toml
This reverts commit 857b1d9b570c5a26643b7ddb9b29bb9ab3f00f8b.
Reason for revert: https://github.com/FooIbar/EhViewer/issues/2355
Resolve #2355
=> Revert "Migrate from Parcelize to kotlinx.serialization"

app/src/main/res/xml-v28/backup_scheme.xml, app/src/main/res/xml/backup_scheme.xml, app/src/main/res/xml/data_extraction_rules.xml
- Fix backup data size quota exceed
- Backup cookies and preferences on Android 9+ (require E2EE)
=> Auto backup improvements

app/build.gradle.kts
=> Do not package OkHttp public suffix list

app/build.gradle.kts, app/src/main/kotlin/com/hippo/ehviewer/ui/main/DownloadCard.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryDetail.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt, gradle/libs.versions.toml
Resolve #2372 
Binary size reduced by 112 KB
=> Remove `ConstraintLayout` usage

app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt, app/src/main/kotlin/com/hippo/ehviewer/legacy/SpiderInfoCompat.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt
We no longer save previews in bundle.
=> Store pToken in `GalleryPreview` and refine parser

app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryPreview.kt, app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt, app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt, app/src/main/kotlin/com/hippo/ehviewer/legacy/SpiderInfoCompat.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderInfo.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt
This reverts commit 5b8d3a282481a22633243423f8d29fe02908572e.
Reason for revert: Reland with fix
Also clear invalid pToken
=> Reapply "Store pToken in `GalleryPreview` and refine parser" (#2390)

app/src/main/kotlin/com/hippo/ehviewer/client/EhUrl.kt
=> Fix torrent url

app/src/main/kotlin/com/hippo/ehviewer/ktor/Common.kt
Why was it needed in the first place?
=> Remove deprecated SaveBodyPlugin

gradle/libs.versions.toml
=> Revert "Update dependency androidx.compose.material3:material3-android to v1.4.0-alpha18"

CHANGELOG.zh-CN.MD
=> Prepare changelog for 1.14.0

app/src/main/kotlin/com/hippo/ehviewer/spider/SpeedTracker.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/settings/DownloadScreen.kt
=> Allow disabling download speed check

app/src/main/kotlin/com/hippo/ehviewer/client/EhTagDatabase.kt, app/src/main/kotlin/com/hippo/ehviewer/client/data/TagNamespace.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/ComicInfo.kt
=> Support new tag namespace: "location:"

app/build.gradle.kts, core/data/src/androidMain/kotlin/com/ehviewer/core/preferences/DataStorePreferences.android.kt
The actual disk I/O will perform in the scope of DataStore.
=> Remove unnecessary JNI lib and main thread check

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
=> Work around crash when dismissing filter settings

app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt, app/src/main/kotlin/com/hippo/ehviewer/dao/DownloadLabelDao.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt, app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt
=> Support searching download labels with `label:`

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt, app/src/main/kotlin/com/hippo/ehviewer/client/exception/FatalException.kt, app/src/main/kotlin/com/hippo/ehviewer/client/exception/QuotaExceededException.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt, app/src/main/kotlin/com/hippo/ehviewer/download/DownloadService.kt, app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt, core/i18n/src/commonMain/moko-resources/base/strings.xml, core/i18n/src/commonMain/moko-resources/zh-rCN/strings.xml
=> Stop downloads and notify the user on fatal errors
