FooIbar/EhViewer

app/src/main/kotlin/com/hippo/ehviewer/ui/EhActivity.kt
app/src/main/res/values/themes.xml

This reverts 216a04309408684c141db1d34114f271cf20cc01.
Reason for revert: Incorrect status bar color when app's night mode setting is different from system's
CC: @nullArrayList

Revert "Set bar style correctly"

---

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
app/src/main/kotlin/com/hippo/ehviewer/client/EhTagDatabase.kt

`updateInternal` and `issueUpdateInMemoryData` will try to create tag database directory at the same time on first launch and one of them will fail, causing app crash

Avoid race condition when updating tag database

---

app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt

But why was it recycled?
Resolve #144

Fix NPE when evicting cache but Image was recycled

---

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/scene/HistoryFragment.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

I don't think we should expose such options to end users, but some people still report that drawer gestures are too sensitive.

Add experimental option to tweak swipe sensitivity

---

app/src/main/kotlin/androidx/swiperefreshlayout/widget/ThemedSwipeRefreshLayout.kt

Don't save it as `onRestoreInstanceState` will be called after loading state has settled
Resolve #209

Fix inconsistent refresh state

---

app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt

Fix crash caused by activity recreate when it's invisible

Close drawer before navigating to another activity

---

app/src/main/rust/src/parser/list.rs

Disallow empty gallery list result

---

README.md
app/build.gradle.kts
app/proguard-rules.pro
app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt
app/src/main/kotlin/eu/kanade/tachiyomi/network/interceptor/UncaughtExceptionInterceptor.kt
docs/README/zh-cn.md
docs/README/zh-tw.md
gradle/libs.versions.toml

This partially reverts commit 7b67210876975d5b63559204c476ea8b50d55e00
Reason for revert: `setApplicationProtocols` used by Apache 5 HC is not available until API 29.
Resolve #514

Revert to use OkHttp as fallback engine

---

app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt

This reverts commit c07d9da7
Reason for revert: Coil provides more precise target size control compared to `ImageDecoder.setTargetSampleSize`.

Revert "Reduce image target size since we are using fill"

---

app/src/main/kotlin/com/hippo/ehviewer/gallery/ArchivePageLoader.kt
app/src/main/kotlin/com/hippo/ehviewer/gallery/EhPageLoader.kt
app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt

`OSUtils.totalMemory` needs to read from disk

Lazily initialize image cache of PageLoader

---

.gitignore
app/.gitignore
app/build.gradle.kts
app/src/main/cpp/CMakeLists.txt
app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts

~This also allows us to enable gradle configuration cache.~
Gradle configuration cache is disabled for now, will try enabling it in the future.

Migrate to Corrosion, rust-android-gradle is dead

---

app/build.gradle.kts

The problem occurs in https://github.com/androidx/androidx/commit/52835066c9044647a65dfb566f03131aab46e793 SlotTable modification.

Enable compiler nonSkippingGroupOptimization

---

app/src/main/cpp/CMakeLists.txt
app/src/main/cpp/hash.c
app/src/main/kotlin/com/hippo/ehviewer/jni/Hash.kt
app/src/main/kotlin/com/hippo/unifile/UniFileExtensions.kt

`kotlinx-io` has removed hash functions API.

Move sha1 digest calculation to native function

---

app/schemas/com.hippo.ehviewer.dao.EhDatabase/20.json
app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
app/src/main/kotlin/com/hippo/ehviewer/EhDB.kt
app/src/main/kotlin/com/hippo/ehviewer/client/data/BaseGalleryInfo.kt
app/src/main/kotlin/com/hippo/ehviewer/dao/Database.kt
app/src/main/kotlin/com/hippo/ehviewer/dao/GalleryDao.kt
app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt

It is expected that most downloads will be in the same language.
BREAKING CHANGE: Upgrade db, add `PAGES` column to `GALLERIES` table

Show pages instead of language in downloads' badge

---

app/src/main/kotlin/com/hippo/ehviewer/coil/CropBorderInterceptor.kt

Webtoons are typically split across multiple pages, they require consistent width to maintain alignment.

Don't crop borders for webtoons

---

CHANGELOG.zh-CN.MD

Should we mention the new reader in changelog or leave it for the next release?

Prepare changelog for 1.11.0

---

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/DownloadsScreen.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Observe the state changes instead of using `confirmValueChange`, which will be called twice

Reintroduce confirm dialog for swipe-to-dismiss

---

app/src/main/kotlin/com/hippo/ehviewer/coil/CropBorderInterceptor.kt
app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt

And don't scale tall images (webtoons).

Scale wide images (banners) to fit target width

---

app/src/main/kotlin/com/hippo/ehviewer/ui/main/DownloadCard.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryInfo.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryHolder.kt

| | | |
| --- | --- | --- |
| Before | ![Screenshot_20240418-164901_Paranoid_Launcher](https://github.com/FooIbar/EhViewer/assets/118464521/3c6b4f4a-cff2-409e-8319-7c0f6deb724c) | ![Screenshot_20240418-170504_Paranoid_Launcher](https://github.com/FooIbar/EhViewer/assets/118464521/53b419de-7762-41ce-9190-7b2ee92f6541) |
| After | ![Screenshot_20240418-233623_Paranoid_Launcher](https://github.com/FooIbar/EhViewer/assets/118464521/dd267024-71bd-48b7-b51a-764c26dbde0c) | ![Screenshot_20240418-234501_Paranoid_Launcher](https://github.com/FooIbar/EhViewer/assets/118464521/f27d2fc3-3aa9-4439-889a-261f0e35eec3) |
Gallery card now has a minimun height of 120 dp to avoid content overlapping.

Tweak gallery card alignment and ensure min height

---

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/SearchBarScreen.kt

Workaround for SearchBar reopen in non-touch mode

---

app/build.gradle.kts

We are not a library intended for Javaers nor do we have any Java code to interop so this is meaningless and safely to drop

Drop `Xjvm-default=all`

---

app/build.gradle.kts
gradle/libs.versions.toml

It's transitively provided by Compose Destinations, we should not directly depend on it in case they are incompatible.

Remove Navigation Compose dependency

---

app/src/main/kotlin/com/hippo/ehviewer/ui/main/TorrentList.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

This reverts commit 49d4ae07
Reason for revert: We list outdated torrents as well after torrent dialog overhaul.

Revert "Clarify message for no current torrents"

---

gradle/libs.versions.toml

This reverts commit 4cea8d0090b0817299954b1ef906f46252baf6c8.
Reason for revert: The item being dragged becomes invisible.

Revert "Update dependency sh.calvin.reorderable:reorderable to v2.0.4"

---

gradle/libs.versions.toml

Reverts FooIbar/EhViewer#1175
Reason for revert: Incompatible with canary AS

Revert "Update dependency com.android.application to v8.5.0-beta01"

---

app/src/main/kotlin/com/hippo/ehviewer/ui/main/ArchiveList.kt

It has fixed size and we don't actually expect its items to be reused.
Resolve #1189

Workaround for archive list crash when scrolling

---

app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/BottomReaderBar.kt

Gotta love those inconsistent platform behaviors

Workaround for navigation bars padding on API < 28

---

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt

Their URLs contain hashes for both original and resampled images.
Resolve #1286

Fix integrity check for non-H@H resampled images

---

gradle/libs.versions.toml

Reverts FooIbar/EhViewer#1325
Reason for revert: `java.lang.NoSuchMethodException: androidx.work.impl.WorkDatabase_Impl.<init> []`

Revert "Update dependency com.android.application to v8.6.0-alpha06"

---

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt
app/src/main/kotlin/com/hippo/ehviewer/Settings.kt
app/src/main/kotlin/com/hippo/ehviewer/coil/CropBorderInterceptor.kt
app/src/main/kotlin/com/hippo/ehviewer/coil/HardwareBitmapInterceptor.kt
app/src/main/kotlin/com/hippo/ehviewer/image/Image.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/settings/AdvancedScreen.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Large hardware bitmaps have rendering issues (e.g. crash, empty) on some devices.
This PR set the hardware bitmap threshold to 8192, which is not ideal but I haven't figured out how to probe that.
All we know is that it's less than the maximum texture size.
Thoughts?
Stack trace for the crash:
```
Abort message: 'glEGLImageTargetTexture2DOES error! GL_INVALID_OPERATION (0x502)'
x0  0000000000000000  x1  0000000000004c64  x2  0000000000000006  x3  0000000000000008
x4  4700000000000000  x5  4700000000000000  x6  4700000000000000  x7  00000000000080c7
x8  0000000000000083  x9  061e566d31eb3741  x10 0000000000000000  x11 fffffffc7ffffbdf
x12 0000000000000001  x13 0000000000000001  x14 ffffffffffffffff  x15 4700000000000000
x16 000000746a3282a8  x17 000000746a247d48  x18 0000000000000010  x19 …
```

Workaround for displaying extremely long images

---

app/build.gradle.kts

Still use 34 SDK in debug build as sources for 35 are not available yet.

Target API 35 as it has reached platform stability

---

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/settings/DownloadScreen.kt

Reason for revert: Caused OOM.
Resolve #1377

Revert "Reuse the root download location UniFile object"

---

app/src/main/kotlin/com/hippo/files/Paths.kt

No need to do it for '?' as that's not allowed in filename.

Fix Path -> Uri conversion

---

app/src/main/cpp/archive.c

This is not available on modern MMU devices

Drop MAP_UNINITIALIZED

---

app/src/main/cpp/archive.c

Practically, `malloc` function family never return 0 on modern system where overcommit is available.
Literally, `GetStringUTFLength` return string char count in utf-8, not including trailing terminator.
Fix #1454

Fix read encrypted archive

---

app/src/main/kotlin/com/hippo/ehviewer/ui/legacy/CoilImageGetter.kt

Seems it's a combined effect of shared element transitions and `Modifier.animateItem`.
I have no idea why this works.
Resolve #1468

Fix layout issue with comments that contain images

---

app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailScreen.kt

Resolve #1525 
The time for composing the header card is negligible, it's the below header content (tags, comments, etc.) causing lag.

Avoid out-of-screen shared element transitions

---

app/src/main/kotlin/com/hippo/ehviewer/ui/reader/GalleryPager.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/reader/PagerViewer.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/reader/ReaderScreen.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/reader/SliderPagerDoubleSync.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/reader/WebtoonViewer.kt

Fix navigation when switching from `WebtoonViewer` to `PagerViewer`.
Hide navigation overlay and reset slider to follow pager on click.

Refine reader

---

app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt
app/src/main/rust/src/parser/home.rs

#1563 
We need to redesign the UI for IP-based ones.
> For IP-based quotas, it will no longer show what the limit is. This is intentional. It will however explicitly tell you on the home screen if your IP is currently restricted from using high-resolution images.
https://forums.e-hentai.org/index.php?showtopic=244935

Fix account-based image limit parsing

---

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt

This reverts commit 822a461acd22e855f2c21c451c351ba14f421975.
https://github.com/FooIbar/EhViewer/issues/1555#issuecomment-2304116084

Fix recent download label can't be set to `null`

---

.github/workflows/ci.yml

1.82.0 has a severe binary size regression (+36%)
```
FILE SIZE        VM SIZE
--------------  --------------
+44%  +131Ki   +44%  +131Ki    .text
+30% +10.7Ki   +30% +10.7Ki    .eh_frame
+6.6% +2.82Ki  +6.6% +2.82Ki    .rodata
+11% +2.58Ki   +11% +2.58Ki    .rela.dyn
+16% +2.41Ki   +16% +2.41Ki    .data.rel.ro
+190% +2.39Ki  +190% +2.39Ki    .gcc_except_table
+22% +1.29Ki   +22% +1.29Ki    .eh_frame_hdr
+16%    +176   +16%    +176    .rela.plt
+12%    +168   +12%    +168    .dynsym
+14%    +112   +14%    +112    .plt
+14%     +56   +14%     +56    .got.plt
+40%     +48   +40%     +48    .data
+1.9%     +24  +1.9%     +24    .dynstr
+14%     +16   +14%     +16    .gnu.version
[ = ]       0  -0.3%      -8    .bss
-3.6%     -16  -3.6%     -16    .dynamic
[ = ]       0 -81.4% -2.36Ki …
```

Pin Rust toolchain version to 1.81.0

---

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt

URLs returned by non-H@H servers may not contain file hash for resampled images.
Resolve #1811

Only check file integrity for images served by H@H

---

app/src/main/kotlin/com/hippo/ehviewer/EhApplication.kt

ConnectivityChecker is not reliable when used with VPN on old platforms.
Resolve #1829

Prevent coil from adding cache-control headers

---

app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderDen.kt
app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt

Propagate errors from `writeComicInfo` to callers

---

app/src/main/kotlin/com/hippo/ehviewer/Settings.kt

Since WebP resamples have smaller file size.

Use desktop User-Agent by default

---

app/src/main/kotlin/com/hippo/ehviewer/ktor/CronetEngine.kt

`ERROR_OTHER` is too generic and contains `ERR_CONTENT_LENGTH_MISMATCH`

Limit the scope of MIUI Cronet workaround

---

gradle.properties
renovate.json

KSP2 is no longer a compiler plugin so the Kotlin version doesn't matter

Clean up renovate config

---

app/build.gradle.kts
benchmark/build.gradle.kts

- Don't generate compatibility bridges and `DefaultImpls` classes
- Remove when guards compiler option as it became stable
- Address deprecation of `kotlinOptions`

Update build scripts for Kotlin 2.2

---

app/src/main/kotlin/com/hippo/ehviewer/client/data/FavListUrlBuilder.kt
app/src/main/kotlin/com/hippo/ehviewer/client/data/ListUrlBuilder.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/FavoritesScreen.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryListScreen.kt

This reverts commit 277deace470c7d6ad30bc49931199e21f59fb777. 
Revert reason: `ListUrlBuilder` doesn't have a qualified `equals` semantics

Revert "MetaState trigger refresh implicitly (#2350)"

---

app/src/main/kotlin/com/hippo/ehviewer/client/data/GalleryPreview.kt
app/src/main/kotlin/com/hippo/ehviewer/client/parser/GalleryDetailParser.kt
app/src/main/kotlin/com/hippo/ehviewer/coil/Extensions.kt
app/src/main/kotlin/com/hippo/ehviewer/legacy/SpiderInfoCompat.kt
app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderInfo.kt
app/src/main/kotlin/com/hippo/ehviewer/spider/SpiderQueen.kt
app/src/main/kotlin/com/hippo/ehviewer/ui/screen/GalleryDetailContent.kt

Reverts FooIbar/EhViewer#2380
Resolve #2389 
This breaks mpv gallery preview parse as well.

Revert "Store pToken in `GalleryPreview` and refine parser"

---

.github/workflows/ci.yml
.github/workflows/releases.yml
app/src/main/cpp/CMakeLists.txt
app/src/main/rust/src/lib.rs
app/src/main/rust/src/parser/archive.rs
app/src/main/rust/src/parser/profile.rs
rust-toolchain.toml

* -10.3% vs nightly-2024-08-30 with backtrace
* +2.8% vs nightly-2024-08-30 without backtrace
I think a 2.8% increase is acceptable (compared to 30+% in #1763) as the cost of updating the toolchain.

Optimize rust binary size

---

app/src/main/kotlin/com/hippo/ehviewer/coil/AnimatedWebPDrawable.kt

The archive may be closed before the decoding job finishes.
This reverts commit 4b25fb8363facfc5868ffcf35b12c855aa44924f.

Actually fix the UAF

---

app/src/main/kotlin/com/hippo/ehviewer/download/DownloadManager.kt
app/src/main/kotlin/com/hippo/ehviewer/spider/SpeedTracker.kt

Subsequent disk I/O will make the reported download speed inaccurate.
Resolve #2545

Stop speed tracker immediately if download is done

---

app/src/main/kotlin/com/hippo/ehviewer/ui/main/GalleryTag.kt

Fixes text visibility on Android 16 QPR1.

Use LocalContentColor.current for tag text
